import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import BuyNow from "./buybutton";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main></main>
      <div className=''>
        {" "}
        content
        <BuyNow />
      </div>
      <footer></footer>
    </div>
  );
}
